name: URL-SHORTENER | ROOT | BACKEND

on:
  push:
    branches:
      - main
    paths:
      - 'apps/url-shortener/backend/**'

jobs:
  deploy:
    name: Deploy URL Shortener Backend
    runs-on: ubuntu-latest
    concurrency: url-shortener-backend-deploy

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --config ./apps/url-shortener/backend/root-backend/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
